vim.opt.foldenable = true
vim.opt.foldopen = "block,insert,jump,mark,percent,quickfix,search,tag,undo"
vim.opt.foldexpr = "v:lua.vim.treesitter.foldexpr()"
vim.opt.foldmethod = "expr"
-- vim.opt.foldtext = "v:lua.vim.treesitter.foldtext()"
vim.opt.foldlevel = 99
vim.opt.foldlevelstart = -1
vim.opt.foldnestmax = 5
vim.opt.foldminlines = 1
vim.opt.fillchars = "fold:·,foldopen:,foldclose:"
